"""Synthesize high-quality speech with Kokoro-82M and optional TCT Broadcast mastering."""
import argparse
import os
import subprocess
import sys
import tempfile

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

MASTER_FILTER = (
    "highpass=f=80,"
    "equalizer=f=140:width_type=h:width=60:g=3.5,"
    "equalizer=f=3600:width_type=h:width=1200:g=4.0,"
    "acompressor=threshold=-16dB:ratio=4:attack=10:release=120:makeup=2.5dB,"
    "loudnorm=I=-14:TP=-1.0:LRA=7"
)

def synthesize(text, voice="em_alex", speed=1.05, output_path=None, master=True, lang="e"):
    try:
        from kokoro import KPipeline
        import soundfile as sf
        import numpy as np
    except ImportError as e:
        print(f"Kokoro dependencies not installed: {e}", file=sys.stderr)
        sys.exit(2)

    pipeline = KPipeline(lang_code=lang, repo_id='hexgrad/Kokoro-82M')
    generator = pipeline(text.strip(), voice=voice, speed=speed)

    chunks = []
    for _, _, audio in generator:
        chunks.append(audio)

    if not chunks:
        raise ValueError("No audio was generated by Kokoro.")

    full_audio = np.concatenate(chunks)
    out_dir = os.path.dirname(os.path.abspath(output_path))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp_wav:
        tmp_wav_path = tmp_wav.name

    try:
        sf.write(tmp_wav_path, full_audio, 24000)

        ffmpeg_bin = os.environ.get("FFMPEG_PATH", "ffmpeg")
        cmd = [ffmpeg_bin, "-y", "-i", tmp_wav_path]
        if master:
            cmd.extend(["-af", MASTER_FILTER])
        cmd.extend(["-c:a", "libmp3lame", "-b:a", "192k", output_path])

        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    finally:
        if os.path.exists(tmp_wav_path):
            try:
                os.remove(tmp_wav_path)
            except OSError:
                pass

def main():
    parser = argparse.ArgumentParser(description="Synthesize speech with Kokoro TTS")
    parser.add_argument("--text", required=True, help="Text to speak")
    parser.add_argument("--voice", default="em_alex", help="Voice ID (e.g. em_alex, ef_dora)")
    parser.add_argument("--speed", type=float, default=1.05, help="Playback speed multiplier")
    parser.add_argument("--out", required=True, help="Output MP3 file path")
    parser.add_argument("--lang", default="e", help="Language code ('e' for Spanish, 'a' for American English)")
    parser.add_argument("--no-master", action="store_true", help="Disable broadcast mastering chain")

    args = parser.parse_args()
    synthesize(
        text=args.text,
        voice=args.voice,
        speed=args.speed,
        output_path=args.out,
        master=not args.no_master,
        lang=args.lang
    )

if __name__ == "__main__":
    main()
