name: Print Secret Temp
on:
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        env:
          MY_SECRET: ${{ secrets.ELEVENLABS_API_KEY }}
        run: |
          echo -n "$MY_SECRET" | od -An -t x1 | tr -d ' \n'
